Web_Market/Pages/Admin/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class LoginModel : PageModel
    {
        private readonly AccountService _accountService;
        [BindProperty]
        public Account account { get; set; }
        public LoginModel(AccountService loginService)
        {
            _accountService = loginService;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Account account)
        {
            try
            {
                string emailorUsername = account.UserName;
                var acc = _accountService.Login(emailorUsername, account.Password);
                if (acc)
                {
                    return Redirect("Index");
                }
                else
                {
                    ViewData["error"] = "Login false";
                    return Page();
                }
            }
            catch (Exception ex)
            {
                ViewData["error"] = "Login false";
                return Page();
            }
        }
        public IActionResult OnGetSignOut()
        {
            _accountService.SignOut();
            return Redirect("/Index");
        }
    }
}

Web_Market/Pages/Admin/profilesetting.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class profilesettingModel : PageModel
    {
        private readonly AccountService _accountService;
        public profilesettingModel(AccountService accountService)
        {
            _accountService = accountService;
        }
        public Account account { get; set; }
        public void OnGet(int id)
        {
            try
            {
                account = _accountService.GetAccountById(id);
            }
            catch (Exception ex)
            {

            }
        }
        public IActionResult OnPostUpdateProfile(Account accountAdd)
        {
            account = _accountService.GetAccountById(accountAdd.AccountId);
            accountAdd.Balance = account.Balance;
            accountAdd.Password = account.Password;
            var update = _accountService.UpdateAccount(accountAdd);
            if (update > 0)
                return Redirect("MagermentAccount");
            return Page();
        }
    }
}

Web_Market/Pages/Category_List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace Web_Market.Pages
{
	public class Category_ListModel : PageModel
	{
		private readonly CategoryService _categoryService;
		private readonly ProductService _productService;

		[BindProperty]
		public Category _category { get; set; }
		public Product? product { get; set; }
		public List<Product> listProduct { get; set; }
        public double? minPrice { get; set; }
        public double? maxPrice { get; set; }
		public List<int> quanCategory { get; set; }
		public int maxPage { get; set; }
        public int curPage { get; set; }
        private int itemsInPage { get; set; } = 15;


        [BindProperty]
		public List<Category>? listCategories { get; set; }
		public Category_ListModel(CategoryService category, ProductService productService)
		{
			_categoryService = category;
			_productService = productService;
		}

		public void OnGet(string? product_name_key, string? category_id_key, int currentpage)
		{
			listCategories = _categoryService.GetAllCategory();
			listProduct = _productService.GetAllProduct().OrderByDescending(x => x.BuyTimes).ToList();
			ViewData["allP"] = listProduct.Count;
			quanCategory = new List<int>();
            foreach (var o in listCategories)
            {
                int count = listProduct.Where(x => x.ProductCategory
				.Contains(o.CategoryId + "")).ToList().Count;
                quanCategory.Add(count);
            }
            if (!string.IsNullOrWhiteSpace(product_name_key) && !string.IsNullOrEmpty(product_name_key))
			{
				listProduct = listProduct.Where(x => x.ProductName
				.ToLower().Contains(product_name_key.ToLower().Trim())
				).ToList();
			}
			if (!string.IsNullOrWhiteSpace(category_id_key) && !string.IsNullOrEmpty(category_id_key))
			{
				listProduct = listProduct.Where(x => x.ProductCategory
				.ToLower().Contains(category_id_key.ToLower().Trim())
				).ToList();
			}
			if (listProduct.Count > 0)
			{
				minPrice = listProduct.MinBy(x => x.Price).Price;
				maxPrice = listProduct.MaxBy(x => x.Price).Price;
				maxPage = listProduct.Count % itemsInPage == 0 ? 
					listProduct.Count / itemsInPage : listProduct.Count / itemsInPage + 1;
			}
			else
			{
				maxPage = 0;
				minPrice = 0;
				maxPrice = 0;
			}
            listProduct = listProduct.Skip(currentpage * itemsInPage).Take(itemsInPage).ToList();
            curPage = currentpage;
            ViewData["search"] = product_name_key;
            ViewData["category"] = category_id_key;

		}
	}
}

Web_Market/Pages/CheckoutCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages
{
    public class CheckoutCartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ObjectModel;
using Service;
using System.Xml;

namespace Web_Market.Pages
{
    public class EditProductModel : PageModel
    {
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly CompanyService _companyService;

        public EditProductModel(CategoryService category, ProductService productService, CompanyService companyService)
        {
            _categoryService = category;
            _productService = productService;
            _companyService = companyService;
        }

        [BindProperty]
        public Product Product { get; set; } = default!;

        [BindProperty]
        public List<String> SelectedCategories { get; set; }
        public List<Company> companies { get; set; } = default!;
        public List<Category> categories { get; set; } = default!;
        public void OnGet(int id)
        {
            Product = _productService.GetProductWithId(id);
            companies = _companyService.GetAllCompany().ToList();
            categories = _categoryService.GetAllCategory().ToList();
            SelectedCategories = Product.ProductCategory.Split(';').ToList();
        }

        
        public async Task<IActionResult> OnPostAsync(Product pro)
        {
            string cate = "";
            for(int i = 0; i < SelectedCategories.Count; i++)
            {
                cate += SelectedCategories[i] + ";";
            }
            pro.ProductCategory = cate.Substring(0, cate.Length - 1);

            _productService.UpdateCategory(pro);

            return RedirectToPage("./Index");
        }
    }
}

Web_Market/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Web_Market.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Web_Market/Pages/Error403.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages
{
    public class Error403Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/ForgotPassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly AccountService _accountService;
        private string emailTochange;
        public ForgotPasswordModel(AccountService loginService)
        {
            _accountService = loginService;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPostForgot(string email)
        {
            try
            {
                var acc = _accountService.GetAccountByEmail(email);
                if (acc != null)
                {
                    ViewData["change"] = "Ok";
                    ViewData["email"] = email;
                    return Page();
                }
                else
                {
                    ViewData["error"] = "Not Found!";
                    return Page();
                }
            }
            catch (Exception ex)
            {
                ViewData["error"] = "Login false";
                return Page();
            }
        }
        public IActionResult OnPostChangePassword(string email, string password)
        {
            var change = _accountService.ChangePass(email, password);
            ViewData["success"] = "Change Pass Done!";
            return Page();
        }
    }
}

Web_Market/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{

    public class IndexModel : PageModel
    {
        private readonly ProductService _product;
        private readonly CategoryService _category;
        private readonly CompanyService _company;
        private readonly AccountService _accountService;

        private readonly ILogger<IndexModel> _logger;

        public List<Product> listProduct { get; set; }
        public List<Category> listCategories { get; set; }
        public List<Company> listCompanies { get; set; }
        private int itemsInPage { get; set; } = 6;
        public int maxPage { get; set; }
        public int curPage { get; set; }

        public IndexModel(ILogger<IndexModel> logger, ProductService product, CategoryService category, CompanyService company)
        {
            _logger = logger;
            _product = product;
            _category = category;
            _company = company;
        }


        public void OnGet(string? keyword, int? category, int? company, int currentPage)
        {
            listProduct = _product.GetAllProduct().OrderByDescending(x => x.BuyTimes).Take(itemsInPage).ToList();
            listCategories = _category.GetAllCategory();
            listCompanies = _company.GetAllCompany();
            if (!string.IsNullOrWhiteSpace(keyword) && !string.IsNullOrEmpty(keyword))
            {
                listProduct = listProduct.Where(x => x.ProductName
                .ToLower().Contains(keyword.ToLower().Trim())
                ).ToList();
            }
            if (category != null)
            {
                listProduct = listProduct.Where(x => x.ProductCategory
                .ToLower().Contains(category + "")
                ).ToList();
            }
            if (company != null)
            {
                listProduct = listProduct.Where(x => x.CompanyId == company).ToList();
            }

            maxPage = listProduct.Count % itemsInPage == 0 ?
                listProduct.Count / itemsInPage :
                listProduct.Count / itemsInPage + 1;
            curPage = currentPage;
            listProduct = listProduct
                .Skip(currentPage * itemsInPage)
                .Take(itemsInPage).ToList();
            ViewData["keyword"] = keyword;
            ViewData["category"] = category;
            ViewData["company"] = company;
        }
    }
}

Web_Market/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Login
{
    public class LoginModel : PageModel
    {
		private readonly AccountService _accountService;
        [BindProperty]
        public Account account { get; set; }
        public LoginModel(AccountService loginService)
        {
            _accountService = loginService;
		}
		public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Account account)
        {
            try
            {
                var acc = _accountService.Login(account.Email, account.Password);
                if (acc)
                {
                   return Redirect("Index");
                }
                else
                {
                    ViewData["error"] = "Login false";
                    return Page();
                }
            }catch(Exception ex)
            {
                ViewData["error"] = "Login false";
                return Page();
            }
        }
        public IActionResult OnGetSignOut()
        {
            _accountService.SignOut();
            return Redirect("Index");
        }
    }
}

Web_Market/Pages/Offer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages
{
    public class OfferModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/OrderDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{
    public class OrderDetailModel : PageModel
    {
        private readonly CartService _cartService;
        private readonly AccountService _accountService;
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly OrderService _orderService;

        public List<Order> listOrders { get; set; }

        public OrderDetailModel(CartService cartService, AccountService accountService, CategoryService categoryService, ProductService productService, OrderService orderService)
        {
            _cartService = cartService;
            _accountService = accountService;
            _categoryService = categoryService;
            _productService = productService;
            _orderService = orderService;
        }

        public void OnGet()
        {
            var UserId = int.Parse(_accountService.GetAccountId());
            listOrders = _orderService.GetAllOrder().Where(x => x.AccountId == UserId).ToList();
        }
    }
}

Web_Market/Pages/Post_Ads.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{
    public class Post_AdsModel : PageModel
    {
        private readonly ProductService _productService;
        private readonly CategoryService _categoryService;
        public List<Category>? listCategory { get; set; }
        public Post_AdsModel(ProductService product,CategoryService categoryService)
        {
            _productService = product;
            _categoryService = categoryService;
        }
        public void OnGet()
        {
            listCategory = new List<Category>();
            listCategory = _categoryService.GetAllCategory();
        }
        public IActionResult OnPostAddProduct(Product product, int[]? ProductCategory)
        {
            try
            {
                product.ProductCategory = String.Join(";", ProductCategory.ToList());
                _productService.AddProduct(product);
                ViewData["message"] = "Add Done";
                listCategory = new List<Category>();
                listCategory = _categoryService.GetAllCategory();
                return Page();
            }catch(Exception ex)
            {
                ViewData["error"] = "Add False";
                listCategory = new List<Category>();
                listCategory = _categoryService.GetAllCategory();
                return Page();
            }
            
        }
    }
}

Web_Market/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/Sign_Up.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{
    public class Sign_UpModel : PageModel
    {
        private readonly AccountService _accountService;
        [BindProperty]
        public Account account { get; set; }
        public Sign_UpModel(AccountService loginService)
        {
            _accountService = loginService;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPostRegister(Account account)
        {
            var acc = _accountService.Register(account);
            if (acc > 0)
                return Redirect("Index");
            return Page();
        }
    }
}

Web_Market/Pages/ForgotPassword.cshtml
@page
@model Web_Market.Pages.ForgotPasswordModel
@{
    Layout = "_Layout";
}
<div class="preloader">
    <div class="loader">
        <div class="ytp-spinner">
            <div class="ytp-spinner-container">
                <div class="ytp-spinner-rotator">
                    <div class="ytp-spinner-left">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                    <div class="ytp-spinner-right">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="banner-area bg_cover">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="banner-content">
                    <h1 class="text-white">Login Page</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-page="index">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Login Page</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="login-area pt-70 pb-70">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-10">
                <div class="login-wrapper box-style">
                    <h3 class="mb-20">Forgot</h3>
                    @{
                        if (ViewBag.change == null)
                        {
                            <form asp-page-handler="forgot" method="post">
                                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                                <div class="row">

                                    <div class="col-12">
                                        <div class="single-form mb-20">
                                            <label class="mb-2">Email of your Acount</label>
                                            <input type="text" id="email" name="email" placeholder="Email" class="py-2 px-3 mb-0 rounded border">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="single-form mb-30">
                                            <button class="main-btn btn-hover py-2 px-5 rounded">Summit</button>
                                            @{
                                                if (ViewBag.success != null)
                                                {
                                                    <span class="text-danger">@ViewBag.success</span>
                                                }
                                            }
                                        </div>
                                    </div>
                                </div>
                            </form>
                        }
                        else
                        {
                            <form asp-page-handler="changepassword" method="post">
                                <div class="col-12">
                                    <div class="single-form mb-20">
                                        <label class="mb-2">New Password</label>
                                        <input type="text" id="mail" name="email" hidden value="@ViewBag.email" />
                                        <input type="password" id="pas" name="Password" placeholder="Password" class="py-2 px-3 mb-0 rounded border">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="single-form mb-30">
                                        <button class="main-btn btn-hover py-2 px-5 rounded">Change</button>
                                        
                                    </div>
                                </div>
                            </form>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</section>


<section class="subscribe-area">
    <div class="container">
        <div class="subscribe-wrapper bg_cover">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="subscribe-content section-title">
                        <h1 class="text-white">Subscribe Our Newsletter</h1>
                        <p class="text-white">Buy and sell everything from used cars to mobile phones and computer or search for property.</p>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="subscribe-form-wrapper">
                        <form action="#" class="subscribe-form">
                            <input type="email" name="sub-email" placeholder="Enter your Email">
                            <button><i class="lni lni-telegram-original"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="client-logo-area pt-140 pb-110">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-xl-6 col-lg-7 col-md-10">
                <div class="text-center section-title mb-60">
                    <h1>Our Trusted Company</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr sed diam nonumy eirmod tempor invidunt ut labore et
                        dolore magna.
                    </p>
                </div>
            </div>
        </div>
        <div class="client-logo-wrapper">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single-logo">
                        <img src="~/images/client-logo/uideck-logo.svg" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-logo">
                        <img src="~/images/client-logo/pagebulb-logo.svg" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-logo">
                        <img src="~/images/client-logo/lineicons-logo.svg" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-logo">
                        <img src="~/images/client-logo/graygrids-logo.svg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<a href="#" class="back-to-top btn-hover"><i class="lni lni-chevron-up"></i></a>

Web_Market/Pages/OrderDetail.cshtml
@page
@model Web_Market.Pages.OrderDetailModel
@{
    Layout = "_Layout";
}
<div class="preloader">
    <div class="loader">
        <div class="ytp-spinner">
            <div class="ytp-spinner-container">
                <div class="ytp-spinner-rotator">
                    <div class="ytp-spinner-left">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                    <div class="ytp-spinner-right">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<section class="banner-area bg_cover">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="banner-content">
                    <h1 class="text-white">
                        My Ads
                    </h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Ads</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="dashboard-area pb-110">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-4">
                <div class="left-sidebar-wrapper box-style">
                    <div class="sidebar-menu">
                        <nav>
                            <ul>
                                <li>
                                    <a asp-page="/admin/dashboard"><i class="lni lni-dashboard"></i>Dashboard</a>
                                </li>
                                <li>
                                    <a asp-page="profile_settings"><i class="lni lni-cog"></i>Profile Settings</a>
                                </li>
                                <li>
                                    <a asp-page="post_ads"><i class="lni lni-cog"></i>Post Ad</a>
                                </li>
                                <li>
                                    <a asp-page="my_ads" class="active"><i class="lni lni-layers"></i>My Ads</a>
                                </li>
                                <li>
                                    <a asp-page="mycart"><i class="lni lni-layers"></i>My Cart</a>
                                </li>
                                <li>
                                    <a asp-page="offer"><i class="lni lni-envelope"></i>Offers / Message</a>
                                </li>
                                <li>
                                    <a asp-page="payments"><i class="lni lni-paypal"></i>Payments</a>
                                </li>
                                <li>
                                    <a asp-page="favorites"><i class="lni lni-heart"></i>My Favorites</a>
                                </li>
                                <li>
                                    <a asp-page="privacy"><i class="lni lni-star"></i>Privacy Settings</a>
                                </li>
                                <li>
                                    <a asp-page="login" asp-page-handler="signout"><i class="lni lni-exit"></i>Sign Out</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-8">
                <div class="dashboard-wrapper box-style">
                    <div class="title">
                        <h3>Order Detail</h3>
                    </div>
                    <div class="card border-top border-bottom border-3" style="border-color: #f37a27 !important;">
          <div class="card-body p-5">

            <p class="lead fw-bold mb-5" style="color: #f37a27;">Purchase Reciept</p>

            <div class="row">
              <div class="col mb-3">
                <p class="small text-muted mb-1">Date</p>
                <p>10 April 2021</p>
              </div>
              <div class="col mb-3">
                <p class="small text-muted mb-1">Order No.</p>
                <p>012j1gvs356c</p>
              </div>
            </div>

            <div class="mx-n5 px-5 py-4" style="background-color: #f2f2f2;">
              <div class="row">
                <div class="col-md-8 col-lg-9">
                  <p>BEATS Solo 3 Wireless Headphones</p>
                </div>
                <div class="col-md-4 col-lg-3">
                  <p>£299.99</p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-8 col-lg-9">
                  <p class="mb-0">Shipping</p>
                </div>
                <div class="col-md-4 col-lg-3">
                  <p class="mb-0">£33.00</p>
                </div>
              </div>
            </div>

            <div class="row my-4">
              <div class="col-md-4 offset-md-8 col-lg-3 offset-lg-9">
                <p class="lead fw-bold mb-0" style="color: #f37a27;">£262.99</p>
              </div>
            </div>

            <p class="lead fw-bold mb-4 pb-2" style="color: #f37a27;">Tracking Order</p>

            <div class="row">
              <div class="col-lg-12">

                <div class="horizontal-timeline">

                  <ul class="list-inline items d-flex justify-content-between">
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white" style="background-color: #f37a27;">Ordered</p
                        class="py-1 px-2 rounded text-white" style="background-color: #f37a27;">
                    </li>
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white" style="background-color: #f37a27;">Shipped</p
                        class="py-1 px-2 rounded text-white" style="background-color: #f37a27;">
                    </li>
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white" style="background-color: #f37a27;">On the way
                      </p>
                    </li>
                    <li class="list-inline-item items-list text-end" style="margin-right: 8px;">
                      <p style="margin-right: -8px;">Delivered</p>
                    </li>
                  </ul>

                </div>

              </div>
            </div>

            <p class="mt-4 pt-2 mb-0">Want any help? <a href="#!" style="color: #f37a27;">Please contact
                us</a></p>

          </div>
        </div>
                </div>
                
            </div>
        </div>
    </div>
</section>