Web_Market/Pages/Admin/HomeAdmin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages.Admin
{
    public class HomeAdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/Admin/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages.Admin
{
    public class HomeAdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/Admin/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class LoginModel : PageModel
    {
        private readonly AccountService _accountService;
        [BindProperty]
        public Account account { get; set; }
        public LoginModel(AccountService loginService)
        {
            _accountService = loginService;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Account account)
        {
            try
            {
                string emailorUsername = account.UserName;
                var acc = _accountService.Login(emailorUsername, account.Password);
                if (acc)
                {
                    return Redirect("Index");
                }
                else
                {
                    ViewData["error"] = "Login false";
                    return Page();
                }
            }
            catch (Exception ex)
            {
                ViewData["error"] = "Login false";
                return Page();
            }
        }
        public IActionResult OnGetSignOut()
        {
            _accountService.SignOut();
            return Redirect("/Index");
        }
    }
}

Web_Market/Pages/Admin/MagermentAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class MagermentAccountModel : PageModel
    {
        private readonly AccountService _accountService;
        public MagermentAccountModel(AccountService accountService)
        {
            _accountService = accountService;
        }
        public List<Account> account { get; set; }
        public void OnGet()
        {
            account = _accountService.listAllAccount().Where(x => x.Type == 1 || x.Type == 2).ToList();
        }
        public IActionResult OnPostBand(int id)
        {
           var check =  _accountService.DeleteAccount(id);
            if(check > 0)
            {
                return new JsonResult(true);
            }
            return new JsonResult(false);
        }
        public IActionResult OnPostActive(int id)
        {
            var check = _accountService.Active(id);
            if (check > 0)
            {
                return new JsonResult(true);
            }
            return new JsonResult(false);
        }
    }
}

Web_Market/Pages/Admin/ManagerProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class ManagerProductModel : PageModel
    {
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly AccountService _accountService;

        public ManagerProductModel(CategoryService categoryService, ProductService productService, AccountService accountService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _accountService = accountService;
        }

        public List<Product> listProduct;
        public List<Product> listProductTop;
        public List<Account> listAccount;

        public IActionResult OnGet(int? account)
        {
            try
            {
                var userID = _accountService.GetAccountId();

                listAccount = _accountService.listAllAccount().Where(x => x.Type == 1)
                    .ToList();

                listProduct = _productService.listAllProduct();

                if (account != null)
                {
                    listProduct = listProduct.Where(x => x.AccountId == account).ToList();
                    ViewData["account"] = account;
                }
                return Page();
            }
            catch(Exception ex)
            {
                return Redirect("/Error403");
            }
        }
        public IActionResult OnPostBand(int id)
        {
            try
            {
                _productService.Band(id);
                return new JsonResult(true);
            }catch(Exception ex)
            {
                return new JsonResult(false);
            }
        }
        public IActionResult OnPostActive(int id)
        {
            try
            {
                _productService.Active(id);
                return new JsonResult(true);
            }
            catch (Exception ex)
            {
                return new JsonResult(false);
            }
        }
    }
}

Web_Market/Pages/Admin/dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Market.Pages
{
    public class dashboardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Web_Market/Pages/Admin/profilesetting.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Admin
{
    public class profilesettingModel : PageModel
    {
        private readonly AccountService _accountService;
        public profilesettingModel(AccountService accountService)
        {
            _accountService = accountService;
        }
        public Account account { get; set; }
        public void OnGet(int id)
        {
            try
            {
                account = _accountService.GetAccountById(id);
            }
            catch (Exception ex)
            {

            }
        }
        public IActionResult OnPostUpdateProfile(Account accountAdd)
        {
            account = _accountService.GetAccountById(accountAdd.AccountId);
            accountAdd.Balance = account.Balance;
            accountAdd.Password = account.Password;
            var update = _accountService.UpdateAccount(accountAdd);
            if (update > 0)
                return Redirect("MagermentAccount");
            return Page();
        }
    }
}

Web_Market/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages.Login
{
    public class LoginModel : PageModel
    {
		private readonly AccountService _accountService;
        [BindProperty]
        public Account account { get; set; }
        public LoginModel(AccountService loginService)
        {
            _accountService = loginService;
		}
		public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Account account)
        {
            try
            {
                var acc = _accountService.Login(account.Email, account.Password);
                if (acc)
                {
                   return Redirect("Index");
                }
                else
                {
                    ViewData["error"] = "Login false";
                    return Page();
                }
            }catch(Exception ex)
            {
                ViewData["error"] = "Login false";
                return Page();
            }
        }
        public IActionResult OnGetSignOut()
        {
            _accountService.SignOut();
            return Redirect("Index");
        }
    }
}

Web_Market/Pages/Profile_Settings.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ObjectModel;
using Service;

namespace Web_Market.Pages
{
    public class Profile_SettingsModel : PageModel
    {
        private readonly AccountService _accountService;
        public Profile_SettingsModel(AccountService accountService)
        {
            _accountService = accountService;
        }
        public Account account { get; set; }
        public void OnGet()
        {
            try
            {
                var id = _accountService.GetAccountId();
                account = _accountService.GetAccountById(int.Parse(id));
            }
            catch(Exception ex)
            {

            }
        }
        public IActionResult OnPostUpdateProfile(Account accountAdd)
        {
            var id = _accountService.GetAccountId();
            account = _accountService.GetAccountById(int.Parse(id));
            accountAdd.Balance = account.Balance;
            accountAdd.Password = account.Password;
            var update = _accountService.UpdateAccount(accountAdd);
            if(update > 0)
                return Redirect("profile_settings");
            return Page();
        }
    }
}

Web_Market/Pages/Admin/HomeAdmin.cshtml
@page
@model Web_Market.Pages.Admin.HomeAdminModel
@{
    Layout = "_Layout";
}

<div class="preloader">
    <div class="loader">
        <div class="ytp-spinner">
            <div class="ytp-spinner-container">
                <div class="ytp-spinner-rotator">
                    <div class="ytp-spinner-left">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                    <div class="ytp-spinner-right">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<section class="banner-area bg_cover">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="banner-content">
                    <h1 class="text-white">
                        Home
                    </h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="homadmin">Home</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="dashboard-area pb-110">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-4">
                <div class="left-sidebar-wrapper box-style">
                    <div class="sidebar-menu">
                        <nav>
                            <ul>
                                <li>
                                    <a asp-page="/admin/dashboard" class="active"><i class="lni lni-dashboard"></i>Dashboard</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/managerproduct"><i class="lni lni-layers"></i>Manager Product</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/magermentaccount"><i class="lni lni-users"></i>Manager Account</a>
                                </li>
                                <li>
                                    <a asp-page="login" asp-page-handler="signout"><i class="lni lni-exit"></i>Sign Out</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-8">
                <div class="dashboard-wrapper box-style">
                    <div class="title">
                        <h3>My Ads</h3>
                    </div>
                    <div class="table-wrapper table-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<a href="#" class="back-to-top btn-hover"><i class="lni lni-chevron-up"></i></a>

Web_Market/Pages/Admin/MagermentAccount.cshtml
@page
@model Web_Market.Pages.Admin.MagermentAccountModel
@{
    Layout = "_Layout";
}
<div class="preloader">
    <div class="loader">
        <div class="ytp-spinner">
            <div class="ytp-spinner-container">
                <div class="ytp-spinner-rotator">
                    <div class="ytp-spinner-left">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                    <div class="ytp-spinner-right">
                        <div class="ytp-spinner-circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="banner-area bg_cover">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="banner-content">
                    <h1 class="text-white">
                        Home
                    </h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="homadmin">Managerment Account</a></li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="dashboard-area pb-110">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-4">

                <div class="left-sidebar-wrapper box-style">
                    <div class="sidebar-header">
                        <div class="info">
                            <h3>HEllO,Admin. Wellcome back!</h3>
                        </div>
                    </div>
                    <div class="sidebar-menu">
                        <nav>
                            <ul>
                                <li>
                                    <a asp-page="/admin/dashboard"><i class="lni lni-dashboard"></i>Dashboard</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/managerproduct"><i class="lni lni-layers"></i>Manager Product</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/magermentaccount" class="active"><i class="lni lni-users"></i>Manager Account</a>
                                </li>
                                <li>
                                    <a asp-page="login" asp-page-handler="signout"><i class="lni lni-exit"></i>Sign Out</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-8">
                <div class="dashboard-wrapper box-style">
                    <div class="title">
                        <h3>Account Managerment</h3>
                        <a asp-page="MagermentAccount" class="btn btn-success">Refresh</a>
                    </div>
                    <div class="table text-start align-middle table-bordered  mb-0">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope ="col">
                                        UserName
                                    </th>
                                    <th scope="col">
                                        Full Name
                                    </th>
                                    <th scope="col">
                                        Money
                                    </th>
                                    <th scope="col">
                                        Phone
                                    </th>
                                    <th scope="col">
                                        Address
                                    </th>
                                    <th scope="col">
                                        Role
                                    </th>
                                    <th scope="col">
                                        Active
                                    </th>
                                    <th scope="col">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var p in Model.account)
                                {
                                    <tr>
                                        <td scope="row">
                                            @p.UserName
                                        </td>
                                        <td scope="row">
                                            @{
                                                var name = p.FirstName + "" + p.LastName;
                                            }
                                            @name
                                        </td>
                                        <td scope ="row">
                                            @p.Balance
                                        </td>
                                        <td scope="row">
                                            @p.PhoneNumber
                                        </td>
                                        <td scope="row">
                                            @p.Address
                                        </td>
                                        <td scope="row">
                                            @if(p.Type == 2)
                                            {
                                                <span class="badge rounded-pill bg-primary">User</span>
                                            }
                                            else
                                            {
                                                <span class="badge rounded-pill bg-warning text-dark">Shop</span>
                                            }
                                        </td>
                                        <td scope="row">
                                            @if (!p.IsActive)
                                            {
                                                <span class="badge rounded-pill bg-danger">BAND</span>
                                            }
                                            else
                                            {
                                                <span class="badge rounded-pill bg-success">ACTIVE</span>
                                            }
                                        </td>
                                        <td scope="row">
                                            <div class="action-btns">
                                                <a asp-page="profilesetting" asp-page-handler="UpdateProfile" asp-route-id="@p.AccountId" class="edit-btn"><i class="lni lni-pencil"></i></a>
                                                @if (p.IsActive)
                                                {
                                                    <a onclick="sayThankyou(@p.AccountId)" class="delete-btn"><i class="lni lni-trash"></i></a>
                                                }
                                                else
                                                {
                                                    <a onclick="sayThankyouActive(@p.AccountId)" class="active"><i class="lni lni-checkmark"></i></a>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    function sayThankyou(idAcc) {
        $.ajax({
            url: '/admin/MagermentAccount?handler=band', // URL của Razor Page handler
            type: 'POST',  // phương thức gửi request
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            data: { id: idAcc }, // dữ liệu gửi đi
            success: function (result) {
                if (JSON.parse(result) == true) {
                    swal("Thank you alot!", "Account Has Band", "success");
                } else {
                    swal("Thank you alot!", "But you must login first", "error");
                }
            },
            error: function (xhr, status, error) {
                swal("Thank you alot!", "Band False", "error");
            }
        });
    }
    function sayThankyouActive(idAcc) {
        $.ajax({
            url: '/admin/MagermentAccount?handler=Active', // URL của Razor Page handler
            type: 'POST',  // phương thức gửi request
            beforeSend: function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            data: { id: idAcc }, // dữ liệu gửi đi
            success: function (result) {
                if (JSON.parse(result) == true) {
                    swal("Thank you alot!", "Account Has Active", "success");
                } else {
                    swal("Thank you alot!", "But you must login first", "error");
                }
            },
            error: function (xhr, status, error) {
                swal("Thank you alot!", "Band False", "error");
            }
        });
    }
</script>

Web_Market/Pages/Admin/profilesetting.cshtml
@page
@model Web_Market.Pages.Admin.profilesettingModel
@{
    Layout = "_Layout";
}

<section class="banner-area bg_cover">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="banner-content">
                    <h1 class="text-white">Profile Settings</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-page="index">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Profile setting</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="dashboard-area pb-110">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-4">
                <div class="left-sidebar-wrapper box-style">
                    <div class="sidebar-header">
                        <div class="info">
                            <h3>HEllO,Admin. Wellcome back!</h3>
                        </div>
                    </div>
                    <div class="sidebar-menu">
                        <nav>
                            <ul>
                                <li>
                                    <a asp-page="/admin/dashboard"><i class="lni lni-dashboard"></i>Dashboard</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/managerproduct"><i class="lni lni-layers"></i>Manager Product</a>
                                </li>
                                <li>
                                    <a asp-page="/admin/magermentaccount" class="active"><i class="lni lni-users"></i>Manager Account</a>
                                </li>
                                <li>
                                    <a asp-page="login" asp-page-handler="signout"><i class="lni lni-exit"></i>Sign Out</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-8">
                <div class="post-ad-wrapper box-style">
                    <div class="title">
                        <h3>Profile Settings</h3>
                    </div>
                    <div class="post-ad-form-wrapper">
                        <form method="post" asp-page-handler="UpdateProfile">
                            <input hidden name="accountid" value="@Model.account.AccountId"/>
                            <div class="row">
                                <div class="right-wrapper pt-50">
                                    <h5 class="mb-25">Edit Profile</h5>
                                    <div class="card-body">
                                        <div class="row gutters">
                                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                                <h6 class="mb-2 text-primary">Personal Details</h6>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="firstName">First Name</label>
                                                    <input type="text" class="form-control" name="FirstName" placeholder="Enter First name" value="@Model.account.FirstName">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="lastName">Last Name</label>
                                                    <input type="text" class="form-control" name="LastName" placeholder="Enter Last Name" value="@Model.account.LastName">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="phone">Phone</label>
                                                    <input type="tel" class="form-control" name="PhoneNumber" placeholder="Enter phone number" value="@Model.account.PhoneNumber">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="email">Email</label>
                                                    <input type="email" class="form-control" name="Email" placeholder="Enter your email" value="@Model.account.Email">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="username">Username</label>
                                                    <input type="text" class="form-control" name="username" placeholder="username" value="@Model.account.UserName">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="type">Type</label>
                                                    <hr>
                                                    @if(Model.account.Type == 1)
                                                    {
                                                        <span>Shop: </span><input type="radio" name="type" value="1" checked>
                                                        <span>User: </span><input type="radio" name="type" value="2">
                                                    }
                                                    else
                                                    {
                                                        <span>Shop: </span><input type="radio" name="type" value="1">
                                                        <span>User: </span><input type="radio" name="type" value="2" checked>
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row gutters">
                                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                                <h6 class="mt-3 mb-2 text-primary">Address</h6>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="adrress">Adrress</label>
                                                    <input type="text" class="form-control" name="Address" placeholder="Adrress" value="@Model.account.Address">
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                                <div class="form-group">
                                                    <label for="ciTy">City</label>
                                                    <input type="text" class="form-control" name="City" placeholder="Enter City" value="@Model.account.City">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="text-right">
                                            <button type="submit" id="submit" name="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>